### ISSUE TITLE
Create feature to 'Copy' result by click of 'Copy' button

### ISSUE THREAD

**Issue by maddypie** [maddypie/PyCalc#1]
Currently 'Copy' button does not do anything. Using ```tkinter```'s ```clipboard_append()``` destroys the content on clipboard once the app is closed. Find a workaround or use any other method to implement this functionality.

If the current content being displayed is an expression, 'Copy' should copy the whole expression to the clipboard.
If the current content being displayed is the calculated result, the content after ```Ans: ``` should be copied to clipboard. 

**Emphasis on having the copied value on clipboard even after the app is closed.**

**Comment by kana800** [comment]
Hi , 
If you haven't figured out a way, I would like to give this a shot 🥅 . 
Let me know!

**Comment by maddypie** [comment]
Go ahead. I would love to know to a better approach than ```ttk.clipboard_append()``` method.
:+1:

**Comment by kana800** [comment]
I found a small solution before I do a Pull Request I want to run it by you 😄 . Module called `pyperclip` can be used to copy the elements in `STORAGE`.  I created a new function called `copytoclipboard` 

```python
def copytoclipboard(): 
      global STORAGE
      return pyperclip.copy("".join(STORAGE[1:]))
```

This works like a charm.

[pyperclip](https://pypi.org/project/pyperclip/)

**Comment by maddypie** [comment]
This is a valid workaround :+1: 

Before creating a PR:
- Add pyperclip import to top of *source.py* like this: ```from pyperclip import copy as to_clipboard```.
- Change ```copytoclipboard``` to ```copy_to_clipboard```.
- Change ```return``` statement appropriately.
