### ISSUE TITLE
Dynamic font size in display label

### ISSUE THREAD

**Issue by maddypie** [maddypie/PyCalc#6]
Currently ```display_label``` is hard coded ```Times 20``` font. When characters to be displayed exceeds **17**, initial characters are sliced off to prevent breaking of ```display_label (TLabel)``` widget ```(grid : row=0, column=0, columnspan=4)```. 

A better approach would be to **reduce** the font size when characters to be displayed exceeds the width of ```display_label```. 
_Note: Currently resizing the window in disabled. So the width of ```display_label``` is constant._

**Comment by akshaysonawaneS** [comment]
Is this issue solved?

**Comment by maddypie** [comment]
@akshaysonawaneS This issue is open. Please feel free to share your ideas on this issue.

**Comment by vartikably** [comment]
Is anyone working on this issue? I would like to work on it.

**Comment by maddypie** [comment]
@vartikably, **no one** is currently working on this issue. Do proceed to work on this. 
Let me know if you want to be assigned to this issue :nerd_face:

**Comment by vartikably** [comment]
@maddypie wanted to know clear a doubt regarding this issue: 
Till what limit the size should be reduced?

**Comment by maddypie** [comment]
@vartikably, Keep it a maximum of **17 characters** in *Times 20* font.
