### ISSUE TITLE
Switching Label to Entry

### ISSUE THREAD

**Issue by nechepurenkoN** [maddypie/PyCalc#7]
Separate issue for #3 . 

Switching from Label to Entry seems more user-friendly but there are two options. The first one is to prohibit typing invalid symbols and the second one is to validate expression when user press "=".

Which one do you prefer?

**Comment by maddypie** [comment]
Prohibiting **invalid symbols** in ```Entry``` widget requires a loop which runs from the start of the program continuously to ```get``` the value from the *Entry* widget. Will that make the program slow? Equating the expression when user presses "=" should definitely by considered.
One downside of using ```Entry``` widget is, it makes the interface look ugly. I am still not sure if there is a way to custom define the **width** of Entry widget. The only option Entry widget provides is the **length** of the box to be rendered. I think, there is more reading for me to do!
![entry](https://user-images.githubusercontent.com/66778010/90358940-16690c00-e075-11ea-8162-f884cca6997a.png)

**Comment by maddypie** [comment]
Keyboard event binding is added in 692e20f497f7550a5401f594a28dab393732891d. Hence using an entry widget is not needed anymore. One advantage of the entry widget is to **paste from the clipboard**. Hopefully, we can come up with a solution to paste from the clipboard. 
I think this issue can be closed and a new issue for **paste from clipboard** *feature-request* can be opened. 

I would love to hear your opinion too :smile:.
