### ISSUE TITLE
Binding buttons in for cycle

### ISSUE THREAD

**Issue by nechepurenkoN** [maddypie/PyCalc#8]
Refers to #3.

> [Today's update](https://github.com/maddypie/PyCalc/blob/master/WIP%20refactoring%20source.py):
> 
> * Function `__put_dot` updated.
> * New class for GUI added.
> * Fatal errors in GUI:
>   
>   * Every button entry (excluding `'='`) results in display of character `'0'`
> 
> I came to a conclusion that `ttk.Button` with **same name** rebinds the `command` to latest definition. Hence this code chunk rebinds every button `command` to `'0'` _(last entry)_:
> 
> ```python
> ...
>     __layout = ['*', '/', 'C', 'AC',
>                 '9', '8', '7', '-',
>                 '6', '5', '4', '+',
>                 '3', '2', '1', '+/-',
>                 '.', '0', '=']
>     ...
> # ln: 170
>         ''' Control Binding '''
>         buttons = []
>         for bt_text in self.__layout[:-1]:
>             bt = ttk.Button(master=keypad)
>             bt['text'] = bt_text
>             bt['command'] = lambda: (self.bt_cmd.into_storage(bt_text),
>                                      self.bt_cmd.show_storage(self.DISPLAY))
>             buttons.append(bt)
> ...
> ```
> 
> Is this conclusion **relevant** or am I getting it wrong?

The problem is we trying to access the variable from outer scope. More detailed explanation: [here](https://stackoverflow.com/questions/7546285/creating-lambda-inside-a-loop).

Thus, the solution is:
```python
    """
    __layout = ['*', '/', 'C', 'AC',
                    '9', '8', '7', '-',
                    '6', '5', '4', '+',
                    '3', '2', '1', '+/-',
                    '.', '0', '=']
    """
    ...
    def __bind_buttons(self):
        functions = {character: (lambda character=character: self.__storage.into_storage(character)) for character
                     in self.__layout if character != "="}
        functions["="] = lambda: self.__refresh_display(self.__calculator.calculate(self.__storage))
        self.__buttons = {character: ttk.Button(command=functions[character], text=character, master=self.__keypad) for
                          character in self.__layout}
```

**Comment by maddypie** [comment]
My sincere apologies for the delayed response, I was away for a while.

Yes, this is interesting. I think I am now getting the hang of using this property, **closure** if I am not wrong. This solves the problem of #3 (...same name rebinds the command to latest definition...).

**Comment by maddypie** [comment]
@nechepurenkoN I have made the commit. This refactors cut down a lot of code and I believe *gui.py* is more readable now. Many thanks for the tip on **accessing variables from outer scope**. 

This additional change was made:
 - ```_layout``` is now a dictionary as some buttons *(ex: +/- sends 'p', Copy sends 'c')* sends an invoke-command different from its button text.

**Comment by nechepurenkoN** [comment]
@maddypie, great! I suppose you rate the benefits this approach brings.
